CREATE DATABASE IF NOT EXISTS EQUIPAMENTOS_SAUDE;
CREATE DATABASE IF NOT EXISTS EMPRESTIMO;

GRANT ALL PRIVILEGES ON EQUIPAMENTOS_SAUDE.* TO 'mysql'@'%';
GRANT ALL PRIVILEGES ON EMPRESTIMO.* TO 'mysql'@'%';